'use strict';
const ME = 'Marloes Venema';

// Personal/homepage links for co-authors. Add an entry here for anyone you want
// linked — the first time their name appears in the list (reading top to bottom)
// will become a link; every later mention of the same name stays plain text.
// Names must match the spelling used in the `authors` arrays below exactly.
const AUTHOR_LINKS = {
  'Doreen Riepel': 'https://provsec.org/doreen.html',
  'Sven Argo': 'https://informatik.rub.de/seceng/personen/argo/',
  // 'Adrian Ackermann': 'https://...',
  'Tim Güneysu': 'https://informatik.rub.de/seceng/',
  'Tanya Verma': 'https://tanyaverma.sh/',
  'Greg Alpár': 'http://www.cs.ru.nl/~gergely/',
  'Jaap-Henk Hoepman': 'https://www.cs.ru.nl/~jhh/',
  'Bart Jacobs': 'https://www.cs.ru.nl/B.Jacobs/',
  'Hanna Schraffenberger': 'https://www.creativecode.org/',
  'Diego F. Aranha': 'https://dfaranha.github.io/',
  'Antonio de la Piedra': 'https://www.delapiedra.org/',
  'Watson Ladd': 'https://kc2kdm.com/',
};

const PUBS = [
  // 2025
  { year: 2025, title: 'pracy: A Practical Compiler for Attribute-Based Encryption in Python',
    href: 'https://eprint.iacr.org/2025/1240',
    authors: ['Sven Argo', 'Marloes Venema', 'Adrian Ackermann', 'Tim Güneysu'],
    venue: 'CHES 2025',
    links: [{ label: 'eprint', href: 'https://eprint.iacr.org/2025/1240' },
            { label: 'code', href: 'https://github.com/lincolncryptools/pracy' }] },
  { year: 2025, title: 'ABE Cubed: Advanced Benchmarking Extensions for ABE Squared',
    href: 'https://eprint.iacr.org/2025/1230',
    authors: ['Sven Argo', 'Marloes Venema', 'Doreen Riepel', 'Tim Güneysu', 'Diego F. Aranha'],
    venue: 'CHES 2025',
    links: [{ label: 'eprint', href: 'https://eprint.iacr.org/2025/1230' },
            { label: 'code', href: 'https://github.com/lincolncryptools/ABE_Cubed' }] },

  // 2024
  { year: 2024, title: 'ISABELLA: Improving Structures of Attribute-Based Encryption Leveraging Linear Algebra',
    href: 'https://eprint.iacr.org/2024/1352',
    authors: ['Doreen Riepel', 'Marloes Venema', 'Tanya Verma'],
    venue: 'ACM CCS 2024',
    links: [{ label: 'eprint', href: 'https://eprint.iacr.org/2024/1352' },
            { label: 'code', href: 'https://github.com/lincolncryptools/ISABELLA' }] },
  { year: 2024, title: 'Using Predicate Extension for Predicate Encryption to Generically Obtain Chosen-Ciphertext Security and Signatures',
    href: 'https://eprint.iacr.org/2023/1947',
    authors: ['Marloes Venema', 'Leon Botros'],
    venue: 'IACR Communications in Cryptology, 2024-1',
    links: [{ label: 'eprint', href: 'https://eprint.iacr.org/2023/1947' },
            { label: 'code', href: 'https://github.com/leonbotros/pe_cca' }] },

  // 2023
  { year: 2023, title: 'ACABELLA: Automated (Crypt)analysis of Attribute-Based Encryption Leveraging Linear Algebra',
    href: 'https://eprint.iacr.org/2023/1274',
    authors: ['Antonio de la Piedra', 'Marloes Venema', 'Greg Alpár'],
    venue: 'ACM CCS 2023',
    links: [{ label: 'eprint', href: 'https://eprint.iacr.org/2023/1274' },
            { label: 'code', href: 'https://github.com/abecryptools/ACABELLA' },
            { label: 'web app', href: 'https://acabella.net/' }] },
  { year: 2023, title: 'Portunus: Re-imagining Access Control in Distributed Systems',
    href: 'https://eprint.iacr.org/2023/094',
    authors: ['Watson Ladd', 'Tanya Verma', 'Marloes Venema', 'Armando Faz-Hernández', 'Brendan McMillion', 'Avani Wildani', 'Nick Sullivan'],
    venue: 'USENIX ATC 2023',
    links: [{ label: 'eprint', href: 'https://eprint.iacr.org/2023/094' },
            { label: 'code', href: 'https://github.com/cloudflare/circl/tree/main/abe/cpabe/tkn20' },
            { label: 'blog', href: 'https://blog.cloudflare.com/inside-geo-key-manager-v2/' },
            { label: 'RWC talk', href: 'https://www.youtube.com/watch?t=1253&v=Xh849Ij3lhU' }] },
  { year: 2023, title: 'PostGuard: Towards Easy and Secure Email Communication',
    href: 'https://repository.ubn.ru.nl/bitstream/handle/2066/292101/292101.pdf?sequence=1&isAllowed=y',
    authors: ['Leon Botros', 'Merel Brandon', 'Bart Jacobs', 'Daniel Ostkamp', 'Hanna Schraffenberger', 'Marloes Venema'],
    venue: 'CHI EA 2023 (Extended Abstracts of the CHI Conference on Human Factors in Computing Systems)',
    links: [] },
  { year: 2023, title: 'GLUE: Generalizing Unbounded Attribute-Based Encryption for Flexible Efficiency Trade-Offs',
    href: 'https://eprint.iacr.org/2022/613',
    authors: ['Marloes Venema', 'Greg Alpár'],
    venue: 'PKC 2023',
    links: [{ label: 'eprint', href: 'https://eprint.iacr.org/2022/613' },
            { label: 'code', href: 'https://github.com/mtcvenema/glue' }] },
  { year: 2023, title: 'A Practical Compiler for Attribute-Based Encryption: New Decentralized Constructions and More',
    href: 'https://eprint.iacr.org/2023/143',
    authors: ['Marloes Venema'],
    venue: 'CT-RSA 2023',
    links: [{ label: 'eprint', href: 'https://eprint.iacr.org/2023/143' }] },
  { year: 2023, title: 'Systematizing Core Properties of Pairing-Based Attribute-Based Encryption to Uncover Remaining Challenges in Enforcing Access Control in Practice',
    href: 'https://eprint.iacr.org/2021/1172',
    authors: ['Marloes Venema', 'Greg Alpár', 'Jaap-Henk Hoepman'],
    venue: 'Designs, Codes and Cryptography 91(1)',
    links: [{ label: 'eprint', href: 'https://eprint.iacr.org/2021/1172' }] },

  // 2022
  { year: 2022, title: 'TinyABE: Unrestricted Ciphertext-Policy Attribute-Based Encryption for Embedded Devices and Low-Quality Networks',
    href: 'https://eprint.iacr.org/2022/569',
    authors: ['Marloes Venema', 'Greg Alpár'],
    venue: 'AFRICACRYPT 2022',
    links: [{ label: 'eprint', href: 'https://eprint.iacr.org/2022/569' },
            { label: 'code', href: 'https://github.com/mtcvenema/tinyabe' }] },
  { year: 2022, title: 'ABE Squared: Accurately Benchmarking Efficiency of Attribute-Based Encryption',
    href: 'https://eprint.iacr.org/2022/038',
    authors: ['Antonio de la Piedra', 'Marloes Venema', 'Greg Alpár'],
    venue: 'TCHES 2022(2)',
    links: [{ label: 'eprint', href: 'https://eprint.iacr.org/2022/038' },
            { label: 'code', href: 'https://github.com/abecryptools/abe_squared' },
            { label: 'talk', href: 'https://www.youtube.com/watch?v=gRH-UNd3VHU' }] },

  // 2021
  { year: 2021, title: 'Practical Attacks Against Attribute-Based Encryption',
    href: 'https://www.blackhat.com/eu-21/briefings/schedule/index.html#practical-attacks-against-attribute-based-encryption-25058',
    authors: ['Antonio de la Piedra', 'Marloes Venema'],
    venue: 'Black Hat Europe 2021, London',
    links: [{ label: 'abstract', href: 'https://www.blackhat.com/eu-21/briefings/schedule/index.html#practical-attacks-against-attribute-based-encryption-25058' },
            { label: 'code', href: 'https://github.com/kudelskisecurity/abeattacks' },
            { label: 'blog', href: 'https://research.kudelskisecurity.com/2021/11/12/practical-attacks-against-attribute-based-encryption/' }] },
  { year: 2021, title: 'A Bunch of Broken Schemes: A Simple yet Powerful Linear Approach to Analyzing Security of Attribute-Based Encryption',
    href: 'https://eprint.iacr.org/2020/460',
    authors: ['Marloes Venema', 'Greg Alpár'],
    venue: 'CT-RSA 2021',
    links: [{ label: 'eprint', href: 'https://eprint.iacr.org/2020/460' }] },

  // Theses
  { year: 'Theses', title: 'Attaining Basically Everything in Attribute-Based Encryption: Simplifying the Design of Practical Schemes via Pair Encodings',
    href: 'https://mtcvenema.nl/thesis',
    authors: ['Marloes Venema'],
    venue: 'PhD thesis, Radboud University Nijmegen, 2023',
    supervisor: 'Dr. Greg Alpár',
    links: [{ label: 'thesis page', href: 'https://mtcvenema.nl/thesis' },
            { label: 'PDF', href: 'https://mtcvenema.nl/Thesis_Marloes_Venema_v2.pdf' }] },
  { year: 'Theses', title: 'Decentralized Attribute-Based Encryption for DECODE',
    href: 'https://www.ru.nl/publish/pages/769526/marloes_venema.pdf',
    authors: ['Marloes Venema'],
    venue: 'Master\'s thesis, Radboud University Nijmegen, 2018',
    supervisor: 'Dr. Jaap-Henk Hoepman',
    links: [{ label: 'PDF', href: 'https://www.ru.nl/publish/pages/769526/marloes_venema.pdf' }] },
  { year: 'Theses', title: '\u201cP = NP\u201d versus Crypto: Lattice-Based Cryptography',
    href: null,
    authors: ['Marloes Venema'],
    venue: 'Bachelor\'s thesis, Radboud University Nijmegen, 2016',
    supervisor: 'Dr. Wieb Bosma',
    links: [] },
];
